/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package leerarchivo;

import java.awt.Color;
import java.io.IOException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.StringReader;
import java.util.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;
import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import javax.swing.JInternalFrame;

import javax.swing.JLayeredPane;


/**
 *
 * @author callo
 */
public class Grafica extends javax.swing.JFrame {
private SimuladorArbolBinario simulador = new SimuladorArbolBinario();
    /**
     * Creates new form Interfaz
     */
    public Grafica() {
        initComponents();
        this.setLocationRelativeTo(null);
        mcarga.setVisible(false);
        mresul.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        carga = new javax.swing.JButton();
        clasifica2 = new javax.swing.JButton();
        limpia = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        previo = new javax.swing.JTextArea();
        Imprecion = new javax.swing.JButton();
        mcarga = new javax.swing.JLabel();
        mresul = new javax.swing.JLabel();
        mresul1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        sinta = new javax.swing.JTextArea();
        mresul2 = new javax.swing.JLabel();
        clasifica1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadoc = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Analizador Lexico Grupo 2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        carga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/vecteezy_upload-icon-sign-symbol-design_9992368_258.png"))); // NOI18N
        carga.setText("cargar ");
        carga.setBorder(null);
        carga.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        carga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaActionPerformed(evt);
            }
        });
        getContentPane().add(carga, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 130, 60));

        clasifica2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/transferir.png"))); // NOI18N
        clasifica2.setText("clasificar");
        clasifica2.setBorder(null);
        clasifica2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clasifica2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasifica2ActionPerformed(evt);
            }
        });
        getContentPane().add(clasifica2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 140, 60));

        limpia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/limpiar.png"))); // NOI18N
        limpia.setText("limpiar");
        limpia.setBorder(null);
        limpia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        limpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiaActionPerformed(evt);
            }
        });
        getContentPane().add(limpia, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 140, 60));

        previo.setColumns(20);
        previo.setRows(5);
        jScrollPane2.setViewportView(previo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 340, 270));

        Imprecion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imprimir.png"))); // NOI18N
        Imprecion.setText("Imprimir");
        Imprecion.setBorder(null);
        Imprecion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Imprecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprecionActionPerformed(evt);
            }
        });
        getContentPane().add(Imprecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 127, 60));

        mcarga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mcarga.setText("Archivo cargado");
        getContentPane().add(mcarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        mresul.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mresul.setText("sintactico");
        getContentPane().add(mresul, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, -1, -1));

        mresul1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mresul1.setForeground(new java.awt.Color(255, 255, 255));
        mresul1.setText(".");
        getContentPane().add(mresul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 30, -1));

        sinta.setColumns(20);
        sinta.setRows(5);
        jScrollPane3.setViewportView(sinta);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 720, 160));

        mresul2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mresul2.setText("Lexico");
        getContentPane().add(mresul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, -1));

        clasifica1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/transferir.png"))); // NOI18N
        clasifica1.setText("clasificar");
        clasifica1.setBorder(null);
        clasifica1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clasifica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasifica1ActionPerformed(evt);
            }
        });
        getContentPane().add(clasifica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 140, 60));

        resultadoc.setColumns(20);
        resultadoc.setRows(5);
        jScrollPane1.setViewportView(resultadoc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 400, 270));

        jMenuBar1.add(jMenu1);

        jMenu2.setText("EXTRA");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("ARBOL SINTACTICO");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   JFileChooser jFileChooser1 = new JFileChooser();
       
        
    private void clasifica2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasifica2ActionPerformed
     
        
        mresul.setVisible(true);

        // TODO add your handling code here:
        try{
        
        probarLexer();
       resultadoc.append("GRUPO 3");
       resultadoc.append("\n Diego Marroquin");
        }
        
        catch(IOException ex){
        
        System.out.println(ex.getMessage());
        }
       
        
    }//GEN-LAST:event_clasifica2ActionPerformed

    private void cargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaActionPerformed
        // TODO add your handling code here:
         mcarga.setVisible(true);
    
        int iResp;
        String strTexto=null;
        ArrayList<String> alLinea=null;
        FileExplorer fmLeeArchivo=null;
        
        try{
        
               iResp=jFileChooser1.showOpenDialog(this);
               if (iResp==jFileChooser1.APPROVE_OPTION){
               
                   fmLeeArchivo = new FileExplorer();
                   alLinea=fmLeeArchivo.leeArchivo(jFileChooser1.getSelectedFile().toString());
                   
                   if(alLinea.size()>0){
                   
                       for(int i=0; i<alLinea.size(); i++){
                       
                       strTexto=(String)alLinea.get(i);
                       previo.append(strTexto+ "\n");
                       
                       }
                       
                   }
                   
                   
               }
        
        
        }
        catch (Exception ex){
                                              
                       ex.printStackTrace();
                       }
    }//GEN-LAST:event_cargaActionPerformed

    private void limpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiaActionPerformed
        // TODO add your handling code here:
            mcarga.setVisible(false);
            mresul.setVisible(false);
             sinta.setVisible(false);
        sinta.setText("");
        previo.setText("");
        resultadoc.setText("");
    }//GEN-LAST:event_limpiaActionPerformed

    private void ImprecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprecionActionPerformed
      try{
      String nombre="";
      JFileChooser file=new JFileChooser();
      file.showSaveDialog(this);
      File guarda =file.getSelectedFile();
     
       if(guarda !=null){ 
          FileWriter save=new FileWriter(guarda+".txt");
          save.append(resultadoc.getText());
          save.close();//cierre y guardad
          JOptionPane.showMessageDialog(null,"El archivo se a guardado satisdactoriamente");
         
       } 
      }catch (IOException ex){
      
              JOptionPane.showMessageDialog(null,"El archivo nose a guardado");
      
      
      }
      
    }//GEN-LAST:event_ImprecionActionPerformed

    private void clasifica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasifica1ActionPerformed
        // TODO add your handling code here:
        String ST = previo.getText();
        Sintax s = new Sintax(new leerarchivo.LexerCup(new StringReader(ST)));
        
        try {
            s.parse();
            sinta.setText("Analisis realizado correctamente");
            sinta.setForeground(new Color(25, 111, 61));
        } catch (Exception ex) {
            Symbol sym = s.getS();
            sinta.setText("Error de sintaxis. Linea: " + (sym.right + 1) + " Columna: " + (sym.left + 1) + ", Texto: \"" + sym.value + "\"");
            sinta.setForeground(Color.red);
        }
        
        
        
    }//GEN-LAST:event_clasifica1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
       
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
          ARBOL ventana2 = new ARBOL();
        ventana2.setVisible(true);
      
    }//GEN-LAST:event_jMenuItem1ActionPerformed





    
    public void probarLexer() throws IOException{
    
    InformacionAnalisis c= new InformacionAnalisis();
    
    File fichero = new File("fichero.txt");
    PrintWriter Writer;
    
    try{
    
        Writer= new PrintWriter(fichero); 
            Writer.print(previo.getText());
                Writer.close();
    
    }catch(FileNotFoundException ex){
  
    }
    
    Reader reader;
    
    reader = new BufferedReader(new FileReader("fichero.txt"));
    Lexer lexer = new Lexer(reader);
    String Resultado="";
    
    while(true){
    
    Tokens tok=lexer.yylex();
    
    if(tok == null){
    
    resultadoc.setText(Resultado);
    return;
    
    }
    
    switch(tok){
    
        case ERROR:
            Resultado=Resultado+"ERROR LEXICO: "+lexer.lexeme+" "+" "+" Linea: "+c.linea+"\n";
            break;
        case ID: case NUMERO:
            Resultado=Resultado+"LEXEMA: "+tok+" "+" "+" "+" "+" TOKENS: "+lexer.lexeme+"\n";
            break;
            default:
            Resultado=Resultado+"LEXEMA: "+tok+" "+" "+" "+" "+" TOKENS: "+lexer.lexeme+"\n";
            break;
    }
    }
    
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Imprecion;
    private javax.swing.JButton carga;
    private javax.swing.JButton clasifica1;
    private javax.swing.JButton clasifica2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton limpia;
    private javax.swing.JLabel mcarga;
    private javax.swing.JLabel mresul;
    private javax.swing.JLabel mresul1;
    private javax.swing.JLabel mresul2;
    private javax.swing.JTextArea previo;
    private javax.swing.JTextArea resultadoc;
    private javax.swing.JTextArea sinta;
    // End of variables declaration//GEN-END:variables
}
